name: Deloy BE to EC2

on:
  push:
    branches:
      - master
    paths:
      - '**'

env:
  JAR_FILE_NAME: 'quanly-0.0.1-SNAPSHOT.jar'
  EC2_HOST: ${{ secrets.HOST }}
  EC2_USERNAME: ${{ secrets.USER_NAME }}
  EC2_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'adopt'
    
      - name: Build JAR
        run: mvn package -DskipTests
      
      - name: Copy JAR to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ env.HOST }}
          username: ${{ env.USER_NAME }}
          key: ${{ env.PRIVATE_KEY }}
          source: 'target/${{ env.JAR_FILE_NAME }}'
          target: '~app'
          
      - name: Deploying ... 
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.HOST }}
          username: ${{ env.USER_NAME }}
          key: ${{ env.PRIVATE_KEY }}
          script: |
            {
              if tmux ls | awk -F: '{print $1}' | grep -wq "deployment"; then
                tmux kill-session -t deployment
              fi
            }
            cd ~/app
            tmux new-session -d -s deployment 'java -jar ${{ env.JAR_FILE_NAME }}'


